### ISSUE TITLE
test_tracker.exe doesn't light up second controller

### ISSUE THREAD

**Issue by KitF** [HipsterSloth/psmove-unity5#14]
I have two controllers paired, but in the test_tracker.exe, only the first one lights up. The second blinks blue during the initialization, but once the camera view comes up it's off.

**Comment by HipsterSloth** [comment]
Yeah I've noticed this issue at work too. I think it's a pretty straight forward fix in [test_tracker.c](https://github.com/HipsterSloth/psmoveapi/blob/master/examples/c/test_tracker.c#L108-L109). It looks like we aren't bothering to update anything but the first controller in the main update loop. I'll try and get a new build of the test_tracker tool in the next few days/

**Comment by HipsterSloth** [comment]
I just merged in a fixed exe for test_tracker. I tested the fix at work where I have two psmove's. If this fixes the issue for I'll close this issue.

**Comment by HipsterSloth** [comment]
Closing this issue since I haven't heard of any new issues.
