### ISSUE TITLE
Very slow tracking

### ISSUE THREAD

**Issue by demonixis** [HipsterSloth/psmove-unity5#23]
Hi,

I don't know if this issue is related to the tracker library of the Unity code but the tracking is very slow. My camera has been installed using Zadig and is correctly detected, but when I start a demo in Unity, the tracking is too slow to be used correctly.

I tried to start PS3 Eye sdl and I get a 30 FPS max. I saw that the PS2 Eye Driver project has merged recently a big change about this kind of issue. Do you use it?

**Comment by HipsterSloth** [comment]
Yeah I definitely build psmoveapi against rovarma's ps3eyedriver multithreading improvements. I have those changes in this [fork/branch](https://github.com/HipsterSloth/PS3EYEDriver/tree/rovarma-optimization), which is used in my fork of [psmoveapi](https://github.com/HipsterSloth/psmoveapi) that psmove-unity5 links against. So you should technically be getting 60fps.

* When you run usbdeview do you see the driver specified is "libusb0" as specified in the [wiki](https://github.com/HipsterSloth/psmove-unity5/wiki/PSEye-Software-Setup-%28Windows%29#pre-install)?
* Do you only have one ps3eye camera connected? 
* Do you have the camera plugged into a usb hub with other cameras? Like a leap motion?
* Have you tried plugging the camera into another usb port?
* Have you tried unplugging the camera, using usbdevview to uninstall all instances of the ps3eye camera (VID/PID: 1415/2000), plugging the camera back in, and re-assigning the libusb driver to the ps3eye?

Those are some of the things that have helped me when I have run into this issue in the past.

**Comment by demonixis** [comment]
Well it was my fault sorry, That was the bad driver. So this issue can be closed.
However I have two questions and I can open another issues if you want.

- I have fixed the code to work with the latest Oculus SDK (IMHO an external SDK is an unnecessary dependency)
- The position tracking doesn't work correctly. When I start test tracker/text opengl it's relatively fast, but not in Unity. Moreover it doesn't move a lot, just some centimeters i think. Have you any idea? As I said I can open another issue ;)

Thanks a lot.

**Comment by HipsterSloth** [comment]
@demonixis Have you run the visual_coregistration tool yet? It's used to compute what the ps3eye camera pose is relative to the hmd tracking camera (which is why we use the external SDK dependency). That should hopefully make the positional tracking work as you would expect. If not, there is some debugging data I can have you give me from the co-registration tool that will let me know if the transform being generated is any good or not.

Sorry about the outdated OculusSDK too. I'm going to check in an updated version this weekend.

Separately, I'm currently on a new camera pose estimation tool that uses OpenCV's solvePnP method instead of trying to align DK2 tracking data with psmove tracking data currently in the coregistration tool (see issue #18). I'm currently trying to get that done this weekend as well.

**Comment by demonixis** [comment]
Hi,

I don't use the Oculus Rift, so I commented the code that uses it. For now your library is the best I have tested, all works great except the position tracking (but it's because I don't use the DK2).

Why is it hard to just use the PSEye? I think that your new solution could be better for all user if it's no more based on the DK2 tracker. I use the OSVR HDK but the PS Move can be used for non VR games too.

In all case, good job ;) Can't wait to see your progress in this side.

**Comment by HipsterSloth** [comment]
@demonixis So the new tool (shown here: https://youtu.be/33cWRaCC9hU) will allow you to just use the ps3eye camera if that's all you need. However if you want to align the tracking space of the psmove controllers to the tracking space of your HMD you have two options:

* Compute that alignment in the camera calibration tool
* Compute that alignment in your application

In your case once this new camera tool is checked in (hopefully by this Wednesday, got a few more bugs to stamp out) you can do the tracking space alignment in your application. I'd like to provide the option to align the OSVR headset too in the calibration tool though. I know nothing about the OSVR API stack so I'm not sure if this is work that is best done in psmoveapi or if I should write a calibration plugin  for OSVR.

**Comment by demonixis** [comment]
That's nice! Keep up the good work, I can't wait to use it into my game. For now I use Kinect, it's a easy  and cheap but it's not convinient when you have to uses buttons. The PS Move is IMHO the best option. But I don't understand why you have to calibrate it like that. How it works on the real PS3 ? Have you to calibrate it like that? Is it a limitation of the SDK?
